title: Pritesh Tupe
description: Personal site with blogs, projects, stories et al.
url: "https://www.priteshtupe.com"

collections:
  foa:
    output: true
  gs:
    output: true
  notes:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "foa"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "gs"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-optional-front-matter

jekyll-minifier:
  uglifier_args:
    harmony: true

sass:
  style: compressed

include:
  - node_modules/uglifier/index.js

optional_front_matter:
  remove_originals: true
