name: Deploy Site

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: "20"
        env:
          NODE_ENV: "production"
          PERSONAL_WEBSITE_MEDIA: ${{ secrets.PERSONAL_WEBSITE_MEDIA }}
      - run: |
          touch .env
          echo PERSONAL_WEBSITE_MEDIA=${{ secrets.PERSONAL_WEBSITE_MEDIA }} >> .env
          npm ci
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: publish-only
          publish_dir: ./docs
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}
